# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clinkding < Formula
  desc "Modern CLI for linkding bookmark manager"
  homepage "https://github.com/daveonkels/clinkding"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daveonkels/clinkding/releases/download/v1.0.0/clinkding_1.0.0_darwin_amd64.tar.gz"
      sha256 "46300591a5af8b8813803f0c45869f25b49bf1e60ec540838255497cb54023ec"

      def install
        bin.install "clinkding"

        # Generate shell completions
        generate_completions_from_executable(bin/"clinkding", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daveonkels/clinkding/releases/download/v1.0.0/clinkding_1.0.0_darwin_arm64.tar.gz"
      sha256 "8916395b452f8d304bfca897f7319e089d1d6604c13b828fc18e5b9a75c78b3a"

      def install
        bin.install "clinkding"

        # Generate shell completions
        generate_completions_from_executable(bin/"clinkding", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daveonkels/clinkding/releases/download/v1.0.0/clinkding_1.0.0_linux_amd64.tar.gz"
      sha256 "980fd256d409f4cc0c0b2f70867f3aec9535bba902a4139962293b8f0b2625e9"
      def install
        bin.install "clinkding"

        # Generate shell completions
        generate_completions_from_executable(bin/"clinkding", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daveonkels/clinkding/releases/download/v1.0.0/clinkding_1.0.0_linux_arm64.tar.gz"
      sha256 "92f3f1612ae8a1ce831a9d508f2772be947c635a55de459e4e5c58fa4c817ccd"
      def install
        bin.install "clinkding"

        # Generate shell completions
        generate_completions_from_executable(bin/"clinkding", "completion")
      end
    end
  end

  test do
    system "#{bin}/clinkding --version"
  end
end
